### ISSUE TITLE
2.0 is coming 

### ISSUE THREAD

**Issue by ProPheT777** [GeniusesOfSymfony/WebSocketBundle#42]
* [x] #39 Push integration with many driver (ZMQ, AMQP) (@cristhianfernandez01, @parhamdoustdar)  
* [x] Ratchet will be replaced by a gos fork
* [ ] New docs with website and more later real application example (chat, notification) :star2:
* [ ] ~~#47 Multiple application routing (@MuddyPaw)~~
* [ ] ~~#38 Pipelining (@ewertoncode)~~
* [ ] Multi threading, load balancing, better performance
* [x] #48 possible use prefix on redis client storage (@damonsson)

**Comment by vittore** [comment]
Any news? Any release date?

Thanks in advance.
v.

**Comment by gittix09** [comment]
Hello!! I just dropped here to say hi and to thank you for this project!! Version 2.0 looks promising!!
Anyway, what is the ETA (approximately)? How much time before v 2.0 is out?

**Comment by patie** [comment]
hi, why Ratchet will be replaced by a gos fork? :|

**Comment by ProPheT777** [comment]
Hi, 

@gittix09 In fact , all the things present in the 2.0 version is already out in the latest version :) v2 will be a clean up. I can't say any date of released because i'm really busy.

@patie In order to have a proper implementation of push integration, I have to insulate the TopicManager to share it across service instead of copy each connection in push service and in topic. I have keep the same namespace it's a fork with patch. The day of ratchet will resolve it, I will remove the fork. Next version will v0.4 and contains an lot of BC break so I think I will release another major version on my side.

**Comment by patie** [comment]
@ProPheT777 which version of WAMP use this lib / which authobahn.js is needed? thx

**Comment by ProPheT777** [comment]
We use Wamp v1 with authoban 0.8 at least. (all is packaged inside the bundle).

**Comment by yleguern64** [comment]
+1

Hello,

Really need v2 WAMP cause of use in ReactJS with last version of autobahn...

**Comment by ProPheT777** [comment]
Ratchet do not plan to use wampV2, so it's not plan for websocketbundle sorry.
